AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Stack for GTA'

Resources:
  VPCGTA: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.31.0.0/16
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 172.31.0.0/24
      VpcId:
        Ref: VPCGTA