RESOURCES:
  VPCGTA: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.60.0.0/16
      # EnableDnsHostnames: Boolean
      # EnableDnsSupport: Boolean
      # InstanceTenancy: String
      # Ipv4IpamPoolId: String
      # Ipv4NetmaskLength: Integer
      # Tags: 
      #   - Tag

# on:
#   push:
#   workflow_dispatch: