on:
  push:
  workflow_dispatch:

jobs:
  cloudformationdeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Install and Import AWS.Tools.CloudFormation
        shell: pwsh
        run: |
            Install-Module -Name AWS.Tools.CloudFormation -Force -AllowClobber -Scope CurrentUser
            Import-Module AWS.Tools.CloudFormation
      - name: Verify AWS CLI Configuration
        run: aws sts get-caller-identity
      - name: Display CloudFormation Template
        run: cat cloudformation-vpc.yml
      - name: Display PowerShell Script
        run: cat deploy.ps1
      - name: Run PS Deploy
        run: pwsh deploy.ps1
